import { ServiceItem } from '@/lib/database/models/service.model';

export const dummyServices: any[] = [
    {
        _id: "1",
        title: "Guitar Tutor",
        description: "I am a guitar tutor and I teach guitar to people who want to learn guitar",
        imageUrl: "https://source.unsplash.com/person-playing-guitar-fCEJGBzAkrU",
        url: "https://www.chrisdlake.com",
        location: "123",
        provider: {
            _id: "65fe9a5396346912b7163251",
            firstName: "Chris do",
            lastName: "Jake",
            location: "Calgary, AB",
            imageUrl: "https://source.unsplash.com/building-beside-body-of-water-during-golden-hour-aNoP6f4P_nY",
            contactNumber: "587-587-5877",
            email: "chrisdojacob@gmail.com",
            website: "chrisd.com",
        },
        servicesOffered: [
            {
                id: "1",
                title: "Beginner Guitar Lessons",
                description: "Learn the basics of guitar playing, including chords, strumming, and fingerpicking.",
                price: "50",
            },
            {
                id: "2",
                title: "Intermediate Guitar Lessons",
                description: "Build on your existing guitar skills with more advanced techniques and music theory.",
                price: "60",
            },
            {
                id: "3",
                title: "Advanced Guitar Lessons",
                description: "Master complex guitar techniques, including soloing, improvisation, and songwriting.",
                price: "70",
            }
        ],
        averageRating: 3.2,
        totalReviews: 12,
        ratingReviewIDs: [],
        category: { _id: "66139dbbef3d91706ad1d17e", name: "Tutor" },
        bookmarked: true,
    },
    {
        _id: "2",
        title: "Cooking Classes",
        description: "Join our cooking classes to learn delicious recipes from around the world, taught by professional chefs.",
        imageUrl: "https://source.unsplash.com/woman-in-black-and-white-striped-long-sleeve-shirt-holding-stainless-steel-bowl-UyEmagArOLY",
        url: "https://www.culinarydelights.com",
        location: "321 Elm Avenue, Anycity, USA",
        provider: {
            _id: "65fe9a5396346912b7163254",
            firstName: "Julia",
            lastName: "Cook",
            location: "Chicago, IL",
            imageUrl: "https://source.unsplash.com/woman-in-black-long-sleeve-shirt-carrying-girl-in-pink-jacket-tHLCjhDCw3M",
            contactNumber: "555-123-4567",
            email: "julia@culinarydelights.com",
            website: "culinarydelights.com",
        },
        servicesOffered: [
            {
                id: "1",
                title: "Italian Cuisine",
                description: "Learn to make classic Italian dishes, including pasta, pizza, and risotto.",
                price: "60",
            },
            {
                id: "2",
                title: "French Pastry",
                description: "Master the art of French pastry making, from croissants to macarons.",
                price: "70",
            },
            {
                id: "3",
                title: "Asian Fusion",
                description: "Explore the flavors of Asia with dishes from Japan, China, and Thailand.",
                price: "80",
            },
            {
                id: "4",
                title: "Vegan Cooking",
                description: "Discover delicious plant-based recipes that are healthy and sustainable.",
                price: "90",
            },
            {
                id: "5",
                title: "Baking Basics",
                description: "Learn the fundamentals of baking, from cakes and cookies to breads and pastries.",
                price: "50",
            },
            {
                id: "6",
                title: "Healthy Eating",
                description: "Get tips and recipes for healthy eating, including meal planning and nutrition advice.",
                price: "55",
            },
            {
                id: "7",
                title: "Kids Cooking",
                description: "Introduce your kids to the joys of cooking with fun and easy recipes they'll love.",
                price: "45",
            },
            {
                id: "8",
                title: "Date Night Dinners",
                description: "Plan a romantic dinner at home with our special date night recipes and tips.",
                price: "65",
            },
            {
                id: "9",
                title: "Holiday Cooking",
                description: "Celebrate the holidays with festive recipes for Thanksgiving, Christmas, and more.",
                price: "75",
            },
            {
                id: "10",
                title: "Cooking Basics",
                description: "Learn essential cooking techniques, knife skills, and kitchen tips for beginners.",
                price: "40",
            },
            {
                id: "11",
                title: "Meal Prep",
                description: "Simplify your week with meal prep recipes and tips for healthy and delicious meals.",
                price: "85",
            },
            {
                id: "12",
                title: "Dessert Making",
                description: "Indulge your sweet tooth with decadent dessert recipes, from cakes and pies to cookies and ice cream.",
                price: "65",
            },
        ],
        averageRating: 4.9,
        totalReviews: 30,
        ratingReviewIDs: [],
        category: { _id: "66139dbbef3d91706ad1d17e", name: "Tutor" },
        bookmarked: true,
    },
    {
        _id: "3",
        title: "Personal Trainer",
        description: "Certified personal trainer offering customized workout plans and one-on-one training sessions to help you achieve your fitness goals.",
        imageUrl: "https://source.unsplash.com/woman-in-black-tank-top-and-black-leggings-doing-yoga-E8VOttj22s4",
        url: "https://www.fitforyou.com",
        location: "456 Pine Street, Anycity, USA",
        provider: {
            _id: "65fe9a5396346912b7163255",
            firstName: "Max",
            lastName: "Fit",
            location: "Miami, FL",
            imageUrl: "https://source.unsplash.com/man-in-blue-crew-neck-shirt-4uj3iZ5m084",
            contactNumber: "123-789-4560",
            email: "max@fitforyou.com",
            website: "fitforyou.com",
        },
        servicesOffered: [],
        averageRating: 4.7,
        totalReviews: 28,
        ratingReviewIDs: [],
        category: { _id: "65fe8fbcfb55d63b100a4d1e", name: "Personal" },
        bookmarked: true,
    },
    {
        _id: "4",
        title: "Language Tutor",
        description: "Experienced language tutor offering personalized lessons in Spanish, French, and German.",
        imageUrl: "https://source.unsplash.com/woman-in-black-sleeveless-top-h6gCRTCxM7o",
        url: "https://www.languagemasters.com",
        location: "789 Maple Street, Anytown, USA",
        provider: {
            _id: "65fe9a5396346912b7163256",
            firstName: "Sophie",
            lastName: "Linguist",
            location: "Seattle, WA",
            imageUrl: "https://source.unsplash.com/woman-in-blue-tank-top-standing-beside-white-wall-TXxiFuQLBKQ",
            contactNumber: "987-654-3210",
            email: "sophie@languagemasters.com",
            website: "languagemasters.com",
        },
        servicesOffered: [],
        averageRating: 4.6,
        totalReviews: 22,
        ratingReviewIDs: [],
        category: { _id: "65fe8fbcfb55d63b100a4d24", name: "Creative" },
        bookmarked: true,
    },
    {
        _id: "65ff3eee12b684b7c98f57a1",
        title: "Photography Lessons",
        description: "Professional photography lessons tailored to your skill level, covering everything from basic camera techniques to advanced composition.",
        imageUrl: "https://source.unsplash.com/man-on-top-of-mountain-taking-pictures-jg-6ARMiaPM",
        url: "https://www.shuttermasters.com",
        location: "123 Main Street, Anytown, USA",
        provider: {
            _id: "65fe9a5396346912b7163257",
            firstName: "Alex",
            lastName: "Shutter",
            location: "San Francisco, CA",
            imageUrl: "https://source.unsplash.com/man-holding-up-canon-dslr-camera-jUAcCtbMb0k",
            contactNumber: "555-123-7890",
            email: "alex@shuttermasters.com",
            website: "shuttermasters.com",
        },
        servicesOffered: [],
        averageRating: 4.9,
        totalReviews: 35,
        ratingReviewIDs: [],
        category: { _id: "65fe8fbcfb55d63b100a4d24", name: "Arts & Crafts" },
        bookmarked: true,
    }
];

export default dummyServices; // Export 'dummyServices' as the default export
