import { UserItem } from '@/lib/database/models/user.model';

export const dummyUsers: UserItem[] = [

    // Home
    // ASAP Plumbers
    {
        _id: "65fe9a5396346912b7163240",
        clerkId: "clerkId1",
        imageUrl: "https://source.unsplash.com/plumber-fixing-pipe-AGYCFDdheQI",
        email: "jack@plumbingforyou.com",
        website: "plumbingforyou.com",
        username: "jackplumber",
        firstName: "Jack",
        lastName: "Plumber",
        location: "New York, NY",
        contactNumber: "123-456-7890",
        serviceIDs: [],
        ratingReviewIDs: [],
    },
    // Soph Cleaning
    {
        _id: "65fe9a5396346912b7163242",
        clerkId: "clerkId2",
        imageUrl: "https://source.unsplash.com/house-cleaning-services-NI8AefHBKbY",
        email: "sophia@cleaningforyou.com",
        website: "cleaningforyou.com",
        username: "sophcleaner",
        firstName: "Sophia",
        lastName: "Cleaner",
        location: "Chicago, IL",
        contactNumber: "345-678-9012",
        serviceIDs: [],
        ratingReviewIDs: [],
    },
    // Noah Lawns
    {
        _id: "65fe9a5396346912b7163243",
        clerkId: "clerkId3",
        imageUrl: "https://source.unsplash.com/lawn-mowing-services-nzj3vSnjJnM",
        email: "noah@lawnforyou.com",
        website: "lawnforyou.com",
        username: "noahlawn",
        firstName: "Noah",
        lastName: "Lawn",
        location: "Houston, TX",
        contactNumber: "456-789-0123",
        serviceIDs: [],
        ratingReviewIDs: [],
    },
    // Home Security System
    {
        _id: "65fe9a5396346912b7163244",
        clerkId: "clerkId4",
        imageUrl: "https://source.unsplash.com/home-security-system-installation-MNzO4aDZPd4",
        contactNumber: "567-890-1234",
        email: "olivia@securityforyou.com",
        website: "securityforyou.com",
        username: "oliviasecurity",
        firstName: "Olivia",
        lastName: "Security",
        location: "Seattle, WA",
        serviceIDs: [],
        ratingReviewIDs: [],
    },
    // Home Organizer
    {
        _id: "65fe9a5396346912b7163245",
        clerkId: "clerkId5",
        imageUrl: "https://source.unsplash.com/home-organizing-services-3XyZxQ3V9gY",
        contactNumber: "678-901-2345",
        email: "liam@organizingforyou.com",
        website: "organizingforyou.com",
        username: "liamorganizer",
        firstName: "Liam",
        lastName: "Organizer",
        location: "San Francisco, CA",
        serviceIDs: [],
        ratingReviewIDs: [],
    },

    // Personal
    // Personal Trainer
    {
        _id: "65fe9a5396346912b7163255",
        clerkId: "clerkId6",
        imageUrl: "https://source.unsplash.com/man-in-blue-crew-neck-shirt-4uj3iZ5m084",
        contactNumber: "123-789-4560",
        email: "max@fitforyou.com",
        website: "fitforyou.com",
        username: "maxfit",
        firstName: "Max",
        lastName: "Fit",
        location: "Miami, FL",
        serviceIDs: [],
        ratingReviewIDs: [],
    },
    // Yoga Instructor
    {
        _id: "65fe9a5396346912b7163256",
        clerkId: "clerkId7",
        imageUrl: "https://source.unsplash.com/woman-in-yoga-pose-beside-body-of-water-Y7H4BMB0gwg",
        contactNumber: "456-789-1230",
        email: "ava@yogaforyou.com",
        website: "yogaforyou.com",
        username: "avayogi",
        firstName: "Ava",
        lastName: "Yogi",
        location: "Los Angeles, CA",
        serviceIDs: [],
        ratingReviewIDs: [],
    },
    // Personal Nutritionist
    {
        _id: "65fe9a5396346912b7163257",
        clerkId: "clerkId8",
        imageUrl: "https://source.unsplash.com/woman-in-blue-long-sleeved-shirt-wearing-eyeglasses-b6odc9GFyDY",
        contactNumber: "789-123-4560",
        email: "emma@nutritionforyou.com",
        website: "nutritionforyou.com",
        username: "emmanutri",
        firstName: "Emma",
        lastName: "Nutri",
        location: "New York, NY",
        serviceIDs: [],
        ratingReviewIDs: [],
    },
    // Life Coach
    {
        _id: "65fe9a5396346912b7163258",
        clerkId: "clerkId9",
        imageUrl: "https://source.unsplash.com/man-in-blue-shirt-sitting-on-chair-beside-table-Z4wN9ns-WIY",
        contactNumber: "234-567-8901",
        email: "ethan@lifecoaching.com",
        website: "lifecoaching.com",
        username: "ethancoach",
        firstName: "Ethan",
        lastName: "Coach",
        location: "Chicago, IL",
        serviceIDs: [],
        ratingReviewIDs: [],
    },
    // Beauty Consultant
    {
        _id: "65fe9a5396346912b7163259",
        clerkId: "clerkId10",
        imageUrl: "https://source.unsplash.com/woman-doing-her-makeup-eN34gxd3-1w",
        contactNumber: "345-678-9012",
        email: "olivia@beautyforyou.com",
        website: "beautyforyou.com",
        username: "oliviabeauty",
        firstName: "Olivia",
        lastName: "Beauty",
        location: "San Francisco, CA",
        serviceIDs: [],
        ratingReviewIDs: [],
    },
    // Finance Advisor
    {
        _id: "65fe9a5396346912b7163260",
        clerkId: "clerkId11",
        imageUrl: "https://source.unsplash.com/man-in-black-suit-6QlHLVg9u7o",
        contactNumber: "456-789-0123",
        email: "noah@financeforyou.com",
        website: "financeforyou.com",
        username: "noahfinance",
        firstName: "Noah",
        lastName: "Finance",
        location: "Houston, TX",
        serviceIDs: [],
        ratingReviewIDs: [],
    },

    // Tech
    // Emily Types
    {
        _id: "65fe9a5396346912b7163290",
        clerkId: "clerkId12",
        imageUrl: "https://source.unsplash.com/editor-editing-texts-on-laptop-gfSUSlVmtC8",
        contactNumber: "123-456-7890",
        email: "emily@editingforyou.com",
        website: "editingforyou.com",
        username: "emilyeditor",
        firstName: "Emily",
        lastName: "Editor",
        location: "New York, NY",
        serviceIDs: [],
        ratingReviewIDs: [],
    },
    // IT Support by David
    {
        _id: "65fe9a5396346912b7163291",
        clerkId: "clerkId13",
        imageUrl: "https://source.unsplash.com/it-support-specialist-at-work-37Y2h5kQxXg",
        contactNumber: "234-567-8901",
        email: "david@itsupportforyou.com",
        website: "itsupportforyou.com",
        username: "davidit",
        firstName: "David",
        lastName: "IT",
        location: "Los Angeles, CA",
        serviceIDs: [],
        ratingReviewIDs: [],
    },
    // Michael Developments
    {
        _id: "65fe9a5396346912b7163292",
        clerkId: "clerkId14",
        imageUrl: "https://source.unsplash.com/developer-at-work-PrwC08Um7X4",
        contactNumber: "345-678-9012",
        email: "michael@developmentforyou.com",
        website: "developmentforyou.com",
        username: "michaeldev",
        firstName: "Michael",
        lastName: "Developer",
        location: "Chicago, IL",
        serviceIDs: [],
        ratingReviewIDs: [],
    },
    // Ethan Cyber Consultancy
    {
        _id: "65fe9a5396346912b7163294",
        clerkId: "clerkId15",
        imageUrl: "https://source.unsplash.com/cybersecurity-consultant-at-work-wbuM2D2YBSw",
        contactNumber: "567-890-1234",
        email: "ethan@cybersecurityforyou.com",
        website: "cybersecurityforyou.com",
        username: "ethancyber",
        firstName: "Ethan",
        lastName: "Cybersecurity",
        location: "Houston, TX",
        serviceIDs: [],
        ratingReviewIDs: [],
    },
    // Cloud Solutions and Aid
    {
        _id: "65fe9a5396346912b7163295",
        clerkId: "clerkId16",
        imageUrl: "https://source.unsplash.com/cloud-solutions-architecture-f8l4VCfCQ3c",
        contactNumber: "678-901-2345",
        email: "aiden@cloudsolutionsforyou.com",
        website: "cloudsolutionsforyou.com",
        username: "aidencloud",
        firstName: "Aiden",
        lastName: "Architect",
        location: "Boston, MA",
        serviceIDs: [],
        ratingReviewIDs: [],
    },
    // Analysis Freelance Soph
    {
        _id: "65fe9a5396346912b7163293",
        clerkId: "clerkId17",
        imageUrl: "https://source.unsplash.com/data-analysis-mltF7xsLvAI",
        contactNumber: "456-789-0123",
        email: "sophia@dataanalysisforyou.com",
        website: "dataanalysisforyou.com",
        username: "sophiaanalyst",
        firstName: "Sophia",
        lastName: "Analyst",
        location: "San Diego, CA",
        serviceIDs: [],
        ratingReviewIDs: [],
    },

    // Advisory
    // Liv Leagal
    {
        _id: "65fe9a5396346912b7163296",
        clerkId: "clerkId18",
        imageUrl: "https://source.unsplash.com/lawyer-legal-advice-Xp5gUHjTprg",
        contactNumber: "789-012-3456",
        email: "olivia@legaladviceforyou.com",
        website: "legaladviceforyou.com",
        username: "olivialegal",
        firstName: "Olivia",
        lastName: "Legal",
        location: "Washington, DC",
        serviceIDs: [],
        ratingReviewIDs: [],
    },
    // Elijah Business
    {
        _id: "65fe9a5396346912b7163297",
        clerkId: "clerkId19",
        imageUrl: "https://source.unsplash.com/business-consulting-at-work-I4I-M8P56e8",
        contactNumber: "890-123-4567",
        email: "elijah@businessconsultingforyou.com",
        website: "businessconsultingforyou.com",
        username: "elijahbusiness",
        firstName: "Elijah",
        lastName: "Consultant",
        location: "San Francisco, CA",
        serviceIDs: [],
        ratingReviewIDs: [],
    },
    // Ava Fiscal
    {
        _id: "65fe9a5396346912b7163298",
        clerkId: "clerkId20",
        imageUrl: "https://source.unsplash.com/financial-advisor-talking-to-client-Ox1Hc4-0twM",
        contactNumber: "901-234-5678",
        email: "ava@financialadvisorforyou.com",
        website: "financialadvisorforyou.com",
        username: "avafiscal",
        firstName: "Ava",
        lastName: "Financial",
        location: "New York, NY",
        serviceIDs: [],
        ratingReviewIDs: [],
    },
    // Marketing by Liam
    {
        _id: "65fe9a5396346912b7163299",
        clerkId: "clerkId21",
        imageUrl: "https://source.unsplash.com/marketing-consulting-at-work-ZdplXik2dpo",
        contactNumber: "012-345-6789",
        email: "liam@marketingconsultingforyou.com",
        website: "marketingconsultingforyou.com",
        username: "liammarketing",
        firstName: "Liam",
        lastName: "Marketing",
        location: "Chicago, IL",
        serviceIDs: [],
        ratingReviewIDs: [],
    },
    // Mia's Advisory
    {
        _id: "65fe9a5396346912b7163300",
        clerkId: "clerkId22",
        imageUrl: "https://source.unsplash.com/investment-advisor-at-work-XkwF7y-LH38",
        contactNumber: "345-678-9012",
        email: "mia@investmentadvisorforyou.com",
        website: "investmentadvisorforyou.com",
        username: "miainvestment",
        firstName: "Mia",
        lastName: "Investment",
        location: "Los Angeles, CA",
        serviceIDs: [],
        ratingReviewIDs: [],
    },
    // HR Consultancy 
    {
        _id: "65fe9a5396346912b7163301",
        clerkId: "clerkId23",
        imageUrl: "https://source.unsplash.com/human-resources-consulting-at-work-41mBBXyr9Xo",
        contactNumber: "456-789-0123",
        email: "noah@hrconsultingforyou.com",
        website: "hrconsultingforyou.com",
        username: "noahhr",
        firstName: "Noah",
        lastName: "HR",
        location: "Seattle, WA",
        serviceIDs: [],
        ratingReviewIDs: [],
    },

    // Creative
    // Fine Art Painting
    {
        _id: "65fe9a5396346912b7163302",
        clerkId: "clerkId24",
        imageUrl: "https://source.unsplash.com/painting-artist",
        contactNumber: "123-456-7890",
        email: "artist@example.com",
        website: "artistwebsite.com",
        username: "artist123",
        firstName: "Alice",
        lastName: "Artist",
        location: "New York, NY",
        serviceIDs: [],
        ratingReviewIDs: []
    },
    // Professional Photography
    {
        _id: "65fe9a5396346912b7163303",
        clerkId: "clerkId25",
        imageUrl: "https://source.unsplash.com/photographer",
        contactNumber: "234-567-8901",
        email: "photographer@example.com",
        website: "photographerwebsite.com",
        username: "photographer321",
        firstName: "Bob",
        lastName: "Photographer",
        location: "Los Angeles, CA",
        serviceIDs: [],
        ratingReviewIDs: []
    },
    // Sculpture Art
    {
        _id: "65fe9a5396346912b7163304",
        clerkId: "clerkId26",
        imageUrl: "https://source.unsplash.com/sculpture-artist",
        contactNumber: "345-678-9012",
        email: "sculptor@example.com",
        website: "sculptorwebsite.com",
        username: "sculptor456",
        firstName: "Charlie",
        lastName: "Sculptor",
        location: "Chicago, IL",
        serviceIDs: [],
        ratingReviewIDs: []
    },
    // Nature Photography
    {
        _id: "65fe9a5396346912b7163305",
        clerkId: "clerkId27",
        imageUrl: "https://source.unsplash.com/nature-photographer",
        contactNumber: "456-789-0123",
        email: "naturephotographer@example.com",
        website: "naturephotographerwebsite.com",
        username: "naturelover789",
        firstName: "Diana",
        lastName: "Photographer",
        location: "San Francisco, CA",
        serviceIDs: [],
        ratingReviewIDs: []
    },
    // Graphic Design
    {
        _id: "65fe9a5396346912b7163306",
        clerkId: "clerkId28",
        imageUrl: "https://source.unsplash.com/graphic-designer",
        contactNumber: "567-890-1234",
        email: "designer@example.com",
        website: "designerwebsite.com",
        username: "designer123",
        firstName: "Emily",
        lastName: "Designer",
        location: "New York, NY",
        serviceIDs: [],
        ratingReviewIDs: []
    },
    // Music Lessons 
    {
        _id: "65fe9a5396346912b7163307",
        clerkId: "clerkId29",
        imageUrl: "https://source.unsplash.com/music-teacher",
        contactNumber: "678-901-2345",
        email: "musician@example.com",
        website: "musicianwebsite.com",
        username: "musiclover456",
        firstName: "Alex",
        lastName: "Musician",
        location: "Los Angeles, CA",
        serviceIDs: [],
        ratingReviewIDs: []
    },

    // Logistic
    // Moving Services
    {
        _id: "65fe9a5396346912b7163308",
        clerkId: "clerkId30",
        imageUrl: "https://source.unsplash.com/moving-company",
        contactNumber: "789-012-3456",
        email: "movingcompany@example.com",
        website: "movingcompanywebsite.com",
        username: "mover123",
        firstName: "Mike",
        lastName: "Mover",
        location: "Chicago, IL",
        serviceIDs: [],
        ratingReviewIDs: []
    },
    // Courier Services
    {
        _id: "65fe9a5396346912b7163309",
        clerkId: "clerkId31",
        imageUrl: "https://source.unsplash.com/courier-delivery",
        contactNumber: "890-123-4567",
        email: "courierservice@example.com",
        website: "courierservicewebsite.com",
        username: "courier456",
        firstName: "Emma",
        lastName: "Courier",
        location: "Houston, TX",
        serviceIDs: [],
        ratingReviewIDs: []
    },
    // Equipment Rental
    {
        _id: "65fe9a5396346912b7163310",
        clerkId: "clerkId32",
        imageUrl: "https://source.unsplash.com/equipment-rental",
        contactNumber: "901-234-5678",
        email: "rentalservice@example.com",
        website: "rentalservicewebsite.com",
        username: "rental789",
        firstName: "Oliver",
        lastName: "Rental",
        location: "Phoenix, AZ",
        serviceIDs: [],
        ratingReviewIDs: []
    },
    // Driver Services
    {
        _id: "65fe9a5396346912b7163313",
        clerkId: "clerkId33",
        imageUrl: "https://source.unsplash.com/driver-service",
        contactNumber: "456-789-0123",
        email: "driver@example.com",
        website: "driverservice.com",
        username: "driverpro",
        firstName: "Emma",
        lastName: "Driver",
        location: "Miami, FL",
        serviceIDs: [],
        ratingReviewIDs: []
    },
    // Catering Service
    {
        _id: "65fe9a5396346912b7163319",
        clerkId: "clerkId34",
        imageUrl: "https://source.unsplash.com/catering-service",
        contactNumber: "912-345-6789",
        email: "cateringservice@example.com",
        website: "cateringserviceprovider.com",
        username: "caterchef",
        firstName: "Liam",
        lastName: "Cater",
        location: "Houston, TX",
        serviceIDs: [],
        ratingReviewIDs: []
    },
    // Pet Sitting Service
    {
        _id: "65fe9a5396346912b7163320",
        clerkId: "clerkId35",
        imageUrl: "https://source.unsplash.com/pet-sitting-service-1",
        contactNumber: "923-456-7890",
        email: "petsitter@example.com",
        website: "petsittingserviceprovider.com",
        username: "petcarepro",
        firstName: "Emma",
        lastName: "PetCare",
        location: "Chicago, IL",
        serviceIDs: [],
        ratingReviewIDs: []
    },

    // Collab
    // Application Development
    {
        _id: "65fe9a5396346912b7163328",
        clerkId: "clerkId36",
        imageUrl: "https://source.unsplash.com/application-development",
        contactNumber: "123-456-7890",
        email: "john@example.com",
        website: "example.com",
        username: "johnappdev",
        firstName: "John",
        lastName: "Doe",
        location: "New York, NY",
        serviceIDs: ["1", "2", "3"],
        ratingReviewIDs: []
    },
    // Cake Baking Workshop
    {
        _id: "65fe9a5396346912b7163329",
        clerkId: "clerkId37",
        imageUrl: "https://source.unsplash.com/cake-baking-workshop",
        contactNumber: "987-654-3210",
        email: "jane@example.com",
        website: "example.com",
        username: "janebaker",
        firstName: "Jane",
        lastName: "Smith",
        location: "Los Angeles, CA",
        serviceIDs: ["1", "2", "3"],
        ratingReviewIDs: []
    },
    // Data Science Bootcamp
    {
        _id: "65fe9a5396346912b7163327",
        clerkId: "clerkId38",
        imageUrl: "https://source.unsplash.com/data-science-bootcamp",
        contactNumber: "456-789-0123",
        email: "noah@example.com",
        website: "example.com",
        username: "noahdatascience",
        firstName: "Noah",
        lastName: "Johnson",
        location: "San Francisco, CA",
        serviceIDs: ["1", "2", "3"],
        ratingReviewIDs: []
    },
    // Photography Workshop
    {
        _id: "65fe9a5396346912b7163326",
        clerkId: "clerkId39",
        imageUrl: "https://source.unsplash.com/photography-workshop",
        contactNumber: "789-012-3456",
        email: "mike@example.com",
        website: "example.com",
        username: "mikephotography",
        firstName: "Mike",
        lastName: "Williams",
        location: "Chicago, IL",
        serviceIDs: ["1", "2", "3"],
        ratingReviewIDs: []
    },
    // Web Development Bootcamp
    {
        _id: "65fe9a5396346912b7163325",
        clerkId: "clerkId40",
        imageUrl: "https://source.unsplash.com/web-development-bootcamp",
        contactNumber: "321-654-9870",
        email: "sara@example.com",
        website: "example.com",
        username: "sarawebdev",
        firstName: "Sara",
        lastName: "Brown",
        location: "Austin, TX",
        serviceIDs: ["1", "2", "3"],
        ratingReviewIDs: []
    },
    // Graphic Design Workshop
    {
        _id: "65fe9a5396346912b7163324",
        clerkId: "clerkId41",
        imageUrl: "https://source.unsplash.com/graphic-design-workshop",
        contactNumber: "012-345-6789",
        email: "alex@example.com",
        website: "example.com",
        username: "alexgraphic",
        firstName: "Alex",
        lastName: "Davis",
        location: "Seattle, WA",
        serviceIDs: ["1", "2", "3"],
        ratingReviewIDs: []
    },

    // Health
    // General Physician
    {
        "_id": "65fe9a5396346912b716332a",
        "clerkId": "clerkId42",
        "imageUrl": "https://source.unsplash.com/general-physician",
        "contactNumber": "123-456-7890",
        "email": "john@example.com",
        "website": "https://www.example.com/john",
        "username": "john",
        "firstName": "John",
        "lastName": "Doe",
        "location": "Anycity, USA",
        "serviceIDs": [],
        "ratingReviewIDs": []
    },
    // Dentist
    {
        "_id": "65fe9a5396346912b716332b",
        "clerkId": "clerkId43",
        "imageUrl": "https://source.unsplash.com/dentist",
        "contactNumber": "456-789-0123",
        "email": "emma@example.com",
        "website": "https://www.example.com/emma",
        "username": "emma",
        "firstName": "Emma",
        "lastName": "Smith",
        "location": "Anycity, USA",
        "serviceIDs": [],
        "ratingReviewIDs": []
    },
    // Pediatrician
    {
        "_id": "65fe9a5396346912b716332b",
        "clerkId": "clerkId43",
        "imageUrl": "https://source.unsplash.com/dentist",
        "contactNumber": "456-789-0123",
        "email": "emma@example.com",
        "website": "https://www.example.com/emma",
        "username": "emma",
        "firstName": "Emma",
        "lastName": "Smith",
        "location": "Anycity, USA",
        "serviceIDs": [],
        "ratingReviewIDs": []
    },
    // Optometrist
    {
        "_id": "65fe9a5396346912b716332d",
        "clerkId": "clerkId45",
        "imageUrl": "https://source.unsplash.com/optometrist",
        "contactNumber": "890-123-4567",
        "email": "michael@example.com",
        "website": "https://www.example.com/michael",
        "username": "michael",
        "firstName": "Michael",
        "lastName": "Brown",
        "location": "Anycity, USA",
        "serviceIDs": [],
        "ratingReviewIDs": []
    },
    // Dermatologist
    {
        "_id": "65fe9a5396346912b716332e",
        "clerkId": "clerkId46",
        "imageUrl": "https://source.unsplash.com/dermatologist",
        "contactNumber": "901-234-5678",
        "email": "olivia@example.com",
        "website": "https://www.example.com/olivia",
        "username": "olivia",
        "firstName": "Olivia",
        "lastName": "Wilson",
        "location": "Anycity, USA",
        "serviceIDs": [],
        "ratingReviewIDs": []
    },
    // Chiropractor
    {
        "_id": "65fe9a5396346912b716332f",
        "clerkId": "clerkId47",
        "imageUrl": "https://source.unsplash.com/chiropractor",
        "contactNumber": "012-345-6789",
        "email": "david@example.com",
        "website": "https://www.example.com/david",
        "username": "david",
        "firstName": "David",
        "lastName": "Jones",
        "location": "Anycity, USA",
        "serviceIDs": [],
        "ratingReviewIDs": []
    },

    // Tutor
    // Guitar Tutor
    {
        _id: "65fe9a5396346912b7163251",
        clerkId: "clerkId48",
        imageUrl: "https://source.unsplash.com/building-beside-body-of-water-during-golden-hour-aNoP6f4P_nY",
        contactNumber: "587-587-5877",
        email: "chrisdojacob@gmail.com",
        website: "chrisd.com",
        username: "chrisdojacob",
        firstName: "Chris do",
        lastName: "Jake",
        location: "Calgary, AB",
        serviceIDs: [],
        ratingReviewIDs: [],
    },
    // Cooking Classes
    {
        _id: "65fe9a5396346912b7163254",
        clerkId: "clerkId49",
        imageUrl: "https://source.unsplash.com/woman-in-black-long-sleeve-shirt-carrying-girl-in-pink-jacket-tHLCjhDCw3M",
        contactNumber: "555-123-4567",
        email: "julia@culinarydelights.com",
        website: "culinarydelights.com",
        username: "juliacook",
        firstName: "Julia",
        lastName: "Cook",
        location: "Chicago, IL",
        serviceIDs: [],
        ratingReviewIDs: [],
    },
    // Language Tutor
    {
        _id: "65fe9a5396346912b7163256",
        clerkId: "clerkId50",
        imageUrl: "https://source.unsplash.com/woman-in-blue-tank-top-standing-beside-white-wall-TXxiFuQLBKQ",
        contactNumber: "987-654-3210",
        email: "sophie@languagemasters.com",
        website: "languagemasters.com",
        username: "sophieling",
        firstName: "Sophie",
        lastName: "Linguist",
        location: "Seattle, WA",
        serviceIDs: [],
        ratingReviewIDs: [],
    },
    // Photography Lessons
    {
        _id: "65fe9a5396346912b7163257",
        clerkId: "clerkId51",
        imageUrl: "https://source.unsplash.com/man-holding-up-canon-dslr-camera-jUAcCtbMb0k",
        contactNumber: "555-123-7890",
        email: "alex@shuttermasters.com",
        website: "shuttermasters.com",
        username: "alexshutter",
        firstName: "Alex",
        lastName: "Shutter",
        location: "San Francisco, CA",
        serviceIDs: [],
        ratingReviewIDs: [],
    },
    // // Yoga Instructor
    {
        _id: "65fe9a5396346912b7163258",
        clerkId: "clerkId52",
        imageUrl: "https://source.unsplash.com/yoga-instructor",
        contactNumber: "789-456-1230",
        email: "emma@yogamasters.com",
        website: "yogamasters.com",
        username: "emma_yoga",
        firstName: "Emma",
        lastName: "Yoga",
        location: "Los Angeles, CA",
        serviceIDs: [],
        ratingReviewIDs: []
    },
    // Math Tutor
    {
        _id: "65fe9a5396346912b7163259",
        clerkId: "clerkId53",
        imageUrl: "https://source.unsplash.com/math-tutor",
        contactNumber: "123-456-7890",
        email: "jason@mathgenius.com",
        website: "mathgenius.com",
        username: "jason_math",
        firstName: "Jason",
        lastName: "Math",
        location: "New York, NY",
        serviceIDs: [],
        ratingReviewIDs: []
    },

];

export default dummyUsers;
